//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDreamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietaryRequirement
    {
        public int Id { get; set; }
        public int GuestID { get; set; }
        public string RequirementType { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
