//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDreamer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventDreamerDBEntities : DbContext
    {
        public EventDreamerDBEntities()
            : base("name=EventDreamerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DietaryRequirement> DietaryRequirements { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VendorCategory> VendorCategories { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    
        public virtual ObjectResult<AnalizaTroskovaDogadjaja_Result> AnalizaTroskovaDogadjaja(Nullable<int> p_EventID)
        {
            var p_EventIDParameter = p_EventID.HasValue ?
                new ObjectParameter("p_EventID", p_EventID) :
                new ObjectParameter("p_EventID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AnalizaTroskovaDogadjaja_Result>("AnalizaTroskovaDogadjaja", p_EventIDParameter);
        }
    
        public virtual ObjectResult<PretragaVendora_Result> PretragaVendora(Nullable<int> p_KategorijaID, Nullable<decimal> p_MaxCijena)
        {
            var p_KategorijaIDParameter = p_KategorijaID.HasValue ?
                new ObjectParameter("p_KategorijaID", p_KategorijaID) :
                new ObjectParameter("p_KategorijaID", typeof(int));
    
            var p_MaxCijenaParameter = p_MaxCijena.HasValue ?
                new ObjectParameter("p_MaxCijena", p_MaxCijena) :
                new ObjectParameter("p_MaxCijena", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PretragaVendora_Result>("PretragaVendora", p_KategorijaIDParameter, p_MaxCijenaParameter);
        }
    }
}
