//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDreamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Id { get; set; }
        public int EventID { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string ExpenseName { get; set; }
        public decimal PlannedAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
